"""removed unquie constraint in set name

Revision ID: 23f1129e7a67
Revises: e7d3a93c3c38
Create Date: 2023-01-29 18:36:23.716097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f1129e7a67'
down_revision = 'e7d3a93c3c38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('set_name_key', 'set', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('set_name_key', 'set', ['name'])
    # ### end Alembic commands ###
