"""Updated Foldr model

Revision ID: 758a99d0b139
Revises: 87e5885ccee7
Create Date: 2022-08-30 14:54:20.252983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758a99d0b139'
down_revision = '87e5885ccee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('folder_name_key', 'folder', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('folder_name_key', 'folder', ['name'])
    # ### end Alembic commands ###
