"""removed unique for word and definition in card

Revision ID: 7daf39ed5036
Revises: 3f5a47e7a006
Create Date: 2023-02-04 16:10:05.911610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7daf39ed5036'
down_revision = '3f5a47e7a006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('card_definition_key', 'card', type_='unique')
    op.drop_constraint('card_word_key', 'card', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('card_word_key', 'card', ['word'])
    op.create_unique_constraint('card_definition_key', 'card', ['definition'])
    # ### end Alembic commands ###
