"""updated card set relationship

Revision ID: 971c96ad3fce
Revises: cd64f0c014bf
Create Date: 2023-01-29 16:45:48.355370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '971c96ad3fce'
down_revision = 'cd64f0c014bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'set_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('card_set_id_fkey', 'card', type_='foreignkey')
    op.create_foreign_key(None, 'card', 'set', ['set_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.create_foreign_key('card_set_id_fkey', 'card', 'set', ['set_id'], ['id'], ondelete='CASCADE')
    op.alter_column('card', 'set_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
