"""updated cascade deletion

Revision ID: a44341ebd647
Revises: 953e8d8ec149
Create Date: 2023-02-04 18:38:17.810377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a44341ebd647'
down_revision = '953e8d8ec149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('card_set_id_fkey', 'card', type_='foreignkey')
    op.create_foreign_key(None, 'card', 'set', ['set_id'], ['id'])
    op.drop_constraint('sentence_card_id_fkey', 'sentence', type_='foreignkey')
    op.create_foreign_key(None, 'sentence', 'card', ['card_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sentence', type_='foreignkey')
    op.create_foreign_key('sentence_card_id_fkey', 'sentence', 'card', ['card_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.create_foreign_key('card_set_id_fkey', 'card', 'set', ['set_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
