"""add Card model

Revision ID: b443bef5eb0e
Revises: af4a34e62a91
Create Date: 2023-01-28 14:07:14.757592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b443bef5eb0e'
down_revision = 'af4a34e62a91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.String(length=255), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.Column('learned', sa.Boolean(), nullable=False),
    sa.Column('learned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['set_id'], ['set.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('definition'),
    sa.UniqueConstraint('word')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    # ### end Alembic commands ###
