"""updated set user relationship

Revision ID: cd64f0c014bf
Revises: d472402911fb
Create Date: 2023-01-29 16:43:37.080152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd64f0c014bf'
down_revision = 'd472402911fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('set', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('set_user_id_fkey', 'set', type_='foreignkey')
    op.create_foreign_key(None, 'set', 'cards_user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'set', type_='foreignkey')
    op.create_foreign_key('set_user_id_fkey', 'set', 'cards_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('set', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
