"""updated sentence to card relationship

Revision ID: e7d3a93c3c38
Revises: 971c96ad3fce
Create Date: 2023-01-29 16:49:49.896287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7d3a93c3c38'
down_revision = '971c96ad3fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sentence', 'card_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('sentence_card_id_fkey', 'sentence', type_='foreignkey')
    op.create_foreign_key(None, 'sentence', 'card', ['card_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sentence', type_='foreignkey')
    op.create_foreign_key('sentence_card_id_fkey', 'sentence', 'card', ['card_id'], ['id'], ondelete='CASCADE')
    op.alter_column('sentence', 'card_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
